package com.aes.model;
// Generated Apr 14, 2016 4:36:50 PM by Hibernate Tools 3.5.0.Final



/**
 * AddressPk generated by hbm2java
 */
public class AddressPk  implements java.io.Serializable {


     private Integer adressPk;

    public AddressPk() {
    }

    public AddressPk(Integer adressPk) {
       this.adressPk = adressPk;
    }
   
    public Integer getAdressPk() {
        return this.adressPk;
    }
    
    public void setAdressPk(Integer adressPk) {
        this.adressPk = adressPk;
    }




}


