package com.aes.model;
// Generated Apr 14, 2016 4:36:50 PM by Hibernate Tools 3.5.0.Final



/**
 * MemberPk generated by hbm2java
 */
public class MemberPk  implements java.io.Serializable {


     private Integer memberPk;

    public MemberPk() {
    }

    public MemberPk(Integer memberPk) {
       this.memberPk = memberPk;
    }
   
    public Integer getMemberPk() {
        return this.memberPk;
    }
    
    public void setMemberPk(Integer memberPk) {
        this.memberPk = memberPk;
    }




}


