package com.aes.model;
// Generated Apr 14, 2016 4:36:50 PM by Hibernate Tools 3.5.0.Final


import java.util.Date;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private int roleId;
     private String roleName;
     private String roleDescription;
     private String createdBy;
     private Date createdDate;

    public Role() {
    }

	
    public Role(int roleId, String roleName) {
        this.roleId = roleId;
        this.roleName = roleName;
    }
    public Role(int roleId, String roleName, String roleDescription, String createdBy, Date createdDate) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.roleDescription = roleDescription;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getRoleDescription() {
        return this.roleDescription;
    }
    
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


