package com.hhiregistry.model;
// Generated 29-Jan-2011 07:49:27 by Hibernate Tools 3.2.4.GA



/**
 * AddressPk generated by hbm2java
 */
public class AddressPk  implements java.io.Serializable {


     private Integer adressPk;

    public AddressPk() {
    }

    public AddressPk(Integer adressPk) {
       this.adressPk = adressPk;
    }
   
    public Integer getAdressPk() {
        return this.adressPk;
    }
    
    public void setAdressPk(Integer adressPk) {
        this.adressPk = adressPk;
    }




}


