package com.hhiregistry.model;
// Generated 29-Jan-2011 07:49:27 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cellgroup generated by hbm2java
 */
public class Cellgroup  implements java.io.Serializable {


     private String groupName;
     private String groupLocation;
     private Integer memberId;
     private String createdBy;
     private Date createdDate;
     private Set members = new HashSet(0);
     private Set members_1 = new HashSet(0);

    public Cellgroup() {
    }

	
    public Cellgroup(String groupName) {
        this.groupName = groupName;
    }
    public Cellgroup(String groupName, String groupLocation, Integer memberId, String createdBy, Date createdDate, Set members, Set members_1) {
       this.groupName = groupName;
       this.groupLocation = groupLocation;
       this.memberId = memberId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.members = members;
       this.members_1 = members_1;
    }
   
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getGroupLocation() {
        return this.groupLocation;
    }
    
    public void setGroupLocation(String groupLocation) {
        this.groupLocation = groupLocation;
    }
   
   

	public Integer getMemberId() {
		return memberId;
	}


	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}


	public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Set getMembers() {
        return this.members;
    }
    
    public void setMembers(Set members) {
        this.members = members;
    }
    public Set getMembers_1() {
        return this.members_1;
    }
    
    public void setMembers_1(Set members_1) {
        this.members_1 = members_1;
    }




}


