package com.hhiregistry.model;
// Generated 29-Jan-2011 07:49:27 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private int groupId;
     private String groupName;
     private String groupDescription;
     private String createdBy;
     private Date createdDate;
     private Set<Member> members = new HashSet<Member>(0);

    public Groups() {
    }

	
    public Groups(int groupId) {
        this.groupId = groupId;
    }
    public Groups(int groupId, String groupName, String groupDescription, String createdBy, Date createdDate,Set members) {
       this.groupId = groupId;
       this.groupName = groupName;
       this.groupDescription = groupDescription;
       this.members = members;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
    }
   
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getGroupDescription() {
        return this.groupDescription;
    }
    
    public void setGroupDescription(String groupDescription) {
        this.groupDescription = groupDescription;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }


	public Set<Member> getMembers() {
		return members;
	}


	public void setMembers(Set<Member> members) {
		this.members = members;
	}
	
	
	public void addMember(Member member){
		
		this.members.add(member);
	}

	@Override
	public boolean equals(Object obj){ 

		if(obj == null) {
			return false;
		}
		if(obj.getClass() != getClass()){
			return false;
		}

		Groups groups = (Groups)obj;
		if(this.groupId == groups.getGroupId()){
			return true;
		}
		return false;
	}

	@Override
	public int hashCode(){
		return groupName.hashCode();
	}




}


