package com.hhiregistry.model;
// Generated 29-Jan-2011 07:49:27 by Hibernate Tools 3.2.4.GA



/**
 * Hhisettings generated by hbm2java
 */
public class Hhisettings  implements java.io.Serializable {


     private int id;
     private Integer type;
     private String description;

    public Hhisettings() {
    }

	
    public Hhisettings(int id) {
        this.id = id;
    }
    public Hhisettings(int id, Integer type, String description) {
       this.id = id;
       this.type = type;
       this.description = description;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


