package com.hhiregistry.model;

// Generated Dec 6, 2011 3:49:26 AM by Hibernate Tools 3.2.4.GA

/**
 * MemberGroups generated by hbm2java
 */
public class MemberGroups implements java.io.Serializable {

	private Integer membergroupsId;
	private Member member;
	private Groups group;

	public MemberGroups() {
	}

	

	public MemberGroups(Integer membergroupsId, Member member, Groups group) {
		super();
		this.membergroupsId = membergroupsId;
		this.member = member;
		this.group = group;
	}



	public Integer getMembergroupsId() {
		return this.membergroupsId;
	}

	public void setMembergroupsId(Integer membergroupsId) {
		this.membergroupsId = membergroupsId;
	}



	public Member getMember() {
		return member;
	}



	public void setMember(Member member) {
		this.member = member;
	}



	public Groups getGroup() {
		return group;
	}



	public void setGroup(Groups group) {
		this.group = group;
	}

	

	
}
