package com.hhiregistry.model;
// Generated 29-Jan-2011 07:49:27 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {

	private Integer memberId;
	private Cellgroup cellgroup;
	private Address address;
	private String name;
	private String surname;
	private String title;
	private Boolean waterBaptised;
	private String employmentStatus;
	private String maritalStatus;
	private Character sex;
	private String phone;
	private String workphone;
	private String cellphone;
	private String email;
	private String createdBy;
	private Date createdDate;
	private Date birthday;
	private Date savedDate;
	private Boolean newMember;
	private Set<Groups> groups = new HashSet<Groups>(0);

	

	public Member() {
	}

	public Member(Integer memberId) {
		this.memberId = memberId;
	}

	public Member(Integer memberId, Cellgroup cellgroup, Address address,
			String name, String surname, String title, Boolean waterBaptised,
			String employmentStatus, Character sex, String phone,
			String workphone, String cellphone, String email, String createdBy,
			Date createdDate, Date birthday, Date savedDate, Set groups,String maritalStatus, Boolean newMember ) {
		this.memberId = memberId;
		this.cellgroup = cellgroup;
		this.address = address;
		this.name = name;
		this.surname = surname;
		this.title = title;
		this.waterBaptised = waterBaptised;
		this.employmentStatus = employmentStatus;
		this.sex = sex;
		this.phone = phone;
		this.workphone = workphone;
		this.cellphone = cellphone;
		this.email = email;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.birthday = birthday;
		this.savedDate = savedDate;
		this.groups = groups;
		this.maritalStatus = maritalStatus;
		this.newMember = newMember;
	}

	
	

	public Integer getMemberId() {
		return memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	public Cellgroup getCellgroup() {
		return this.cellgroup;
	}

	public void setCellgroup(Cellgroup cellgroup) {
		this.cellgroup = cellgroup;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Boolean getWaterBaptised() {
		return this.waterBaptised;
	}

	public void setWaterBaptised(Boolean waterBaptised) {
		this.waterBaptised = waterBaptised;
	}

	public String getEmploymentStatus() {
		return this.employmentStatus;
	}

	public void setEmploymentStatus(String employmentStatus) {
		this.employmentStatus = employmentStatus;
	}

	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getWorkphone() {
		return this.workphone;
	}

	public void setWorkphone(String workphone) {
		this.workphone = workphone;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Date getSavedDate() {
		return this.savedDate;
	}

	public void setSavedDate(Date savedDate) {
		this.savedDate = savedDate;
	}

	public Set<Groups> getGroups() {
		return groups;
	}

	public void setGroups(Set<Groups> groups) {
		this.groups = groups;
	}
	
	
	public void addGroup(Groups groups){
		
		this.groups.add(groups);
	}
	
	public Boolean getNewMember() {
		return newMember;
	}

	public void setNewMember(Boolean newMember) {
		this.newMember = newMember;
	}
	
	
	@Override
	public boolean equals(Object obj){ 

		if(obj == null) {
			return false;
		}
		if(obj.getClass() != getClass()){
			return false;
		}

		Member member = (Member)obj;
		if(this.memberId == member.getMemberId()){
			return true;
		}
		return false;
	}

	@Override
	public int hashCode(){
		return name.hashCode();
	}

	public String getMaritalStatus() {
		return maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	






}


