package com.aes.data.domain;
// Generated Apr 15, 2016 9:32:00 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private int clientId;
	private Address address;
	private Person person;
	private String clientName;
	private String description;
	private String createdBy;
	private Date createdDate;
	private Set<SurveyClient> surveyClients = new HashSet<SurveyClient>(0);

	public Client() {
	}

	public Client(int clientId, Address address, Person person) {
		this.clientId = clientId;
		this.address = address;
		this.person = person;
	}

	public Client(int clientId, Address address, Person person, String clientName, String description, String createdBy,
			Date createdDate, Set<SurveyClient> surveyClients) {
		this.clientId = clientId;
		this.address = address;
		this.person = person;
		this.clientName = clientName;
		this.description = description;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.surveyClients = surveyClients;
	}

	public int getClientId() {
		return this.clientId;
	}

	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Set<SurveyClient> getSurveyClients() {
		return this.surveyClients;
	}

	public void setSurveyClients(Set<SurveyClient> surveyClients) {
		this.surveyClients = surveyClients;
	}

}
