package com.aes.data.domain;
// Generated Apr 14, 2016 5:52:50 PM by Hibernate Tools 3.5.0.Final

/**
 * PersonRole generated by hbm2java
 */
public class PersonRole implements java.io.Serializable {

	private PersonRoleId id;

	public PersonRole() {
	}

	public PersonRole(PersonRoleId id) {
		this.id = id;
	}

	public PersonRoleId getId() {
		return this.id;
	}

	public void setId(PersonRoleId id) {
		this.id = id;
	}

}
