package com.aes.data.domain;
// Generated Apr 14, 2016 5:59:27 PM by Hibernate Tools 3.5.0.Final

/**
 * PersonRoleId generated by hbm2java
 */
public class PersonRoleId implements java.io.Serializable {

	private Integer personroleId;
	private Integer personId;
	private Integer roleId;

	public PersonRoleId() {
	}

	public PersonRoleId(Integer personroleId, Integer personId, Integer roleId) {
		this.personroleId = personroleId;
		this.personId = personId;
		this.roleId = roleId;
	}

	public Integer getPersonroleId() {
		return this.personroleId;
	}

	public void setPersonroleId(Integer personroleId) {
		this.personroleId = personroleId;
	}

	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonRoleId))
			return false;
		PersonRoleId castOther = (PersonRoleId) other;

		return ((this.getPersonroleId() == castOther.getPersonroleId()) || (this.getPersonroleId() != null
				&& castOther.getPersonroleId() != null && this.getPersonroleId().equals(castOther.getPersonroleId())))
				&& ((this.getPersonId() == castOther.getPersonId()) || (this.getPersonId() != null
						&& castOther.getPersonId() != null && this.getPersonId().equals(castOther.getPersonId())))
				&& ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null
						&& castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPersonroleId() == null ? 0 : this.getPersonroleId().hashCode());
		result = 37 * result + (getPersonId() == null ? 0 : this.getPersonId().hashCode());
		result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		return result;
	}

}
