package com.aes.data.domain;
// Generated Apr 15, 2016 4:26:55 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * SurveyReadings generated by hbm2java
 */
public class SurveyReadings implements java.io.Serializable {

	private int readingId;
	private Survey survey;
	private String location;
	private String readingType;
	private String unit;
	private String value;
	private String description;
	private String createdBy;
	private Date createdDate;

	public SurveyReadings() {
	}

	public SurveyReadings(int readingId, Survey survey) {
		this.readingId = readingId;
		this.survey = survey;
	}

	public SurveyReadings(int readingId, Survey survey, String location, String readingType, String unit, String value,
			String description, String createdBy, Date createdDate) {
		this.readingId = readingId;
		this.survey = survey;
		this.location = location;
		this.readingType = readingType;
		this.unit = unit;
		this.value = value;
		this.description = description;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public int getReadingId() {
		return this.readingId;
	}

	public void setReadingId(int readingId) {
		this.readingId = readingId;
	}

	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getReadingType() {
		return this.readingType;
	}

	public void setReadingType(String readingType) {
		this.readingType = readingType;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
