package com.aes.data.domain;
// Generated Apr 15, 2016 4:26:55 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String username;
	private Person person;
	private String password;
	private String createdBy;
	private Date createdDate;
	private Set<Survey> surveys = new HashSet<Survey>(0);
	private Set<Role> roles = new HashSet<Role>(0);

	public User() {
	}

	public User(String username, Person person, String password) {
		this.username = username;
		this.person = person;
		this.password = password;
	}

	public User(String username, Person person, String password, String createdBy, Date createdDate,
			Set<Survey> surveys, Set<Role> roles) {
		this.username = username;
		this.person = person;
		this.password = password;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.surveys = surveys;
		this.roles = roles;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Set<Survey> getSurveys() {
		return this.surveys;
	}

	public void setSurveys(Set<Survey> surveys) {
		this.surveys = surveys;
	}

	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
